apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: test
  source:
    path: test
    repoURL: git@github.com:oleg-batyuk/helm-test.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
